name: Fourth-April

on:
  push:
    branches: [ main ]

jobs:
  kuch-bhi:
    runs-on: ubuntu-latest

    steps:
      - name: Tayyab's Task
        run: echo "I have successfully exectued my first workflow"
